app/routes/acteur.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from markupsafe import Markup
from app.forms.forms import ActeurForm
from app.models.models import Acteur, Film, Rol
from app import db

acteur_bp = Blueprint('acteur', __name__, url_prefix='/acteur')

@acteur_bp.route('/', methods=['GET'])
def acteurs():
    search_query = request.args.get('search', '')
    if search_query:
        acteurs:list[Acteur] = Acteur.query.filter(
            db.or_(
                Acteur.voornaam.ilike(f'%{search_query}%'),
                Acteur.achternaam.ilike(f'%{search_query}%')
            )
        ).all()
    else:
        acteurs:list[Acteur] = Acteur.query.all()
    
    return render_template('acteur/acteurs.html', acteurs=acteurs)


@acteur_bp.route('/add', methods=['GET', 'POST'])
@login_required
def acteur_add():
    form:ActeurForm = ActeurForm()
    if form.validate_on_submit():
        acteur:Acteur = Acteur(voornaam=form.voornaam.data, achternaam=form.achternaam.data)
        db.session.add(acteur)
        db.session.commit()
        flash('De acteur is succesvol toegevoegd!', 'success')
        return redirect(url_for('acteur.acteurs'))
    return render_template('acteur/acteur_add.html', form=form)


@acteur_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def acteur_edit(id):
    acteur:Acteur = Acteur.query.get_or_404(id)
    form = ActeurForm(obj=acteur)
    
    if form.validate_on_submit():
        acteur.voornaam = form.voornaam.data
        acteur.achternaam = form.achternaam.data
        
        db.session.commit()
        flash('De acteur is succesvol bijgewerkt!', 'success')
        return redirect(url_for('acteur.acteurs', id=acteur.id))
    
    return render_template('acteur/acteur_edit.html', form=form)


@acteur_bp.route('/delete/<int:id>', methods=['GET'])
@login_required
def acteur_delete(id):
    acteur:list[Acteur] = Acteur.query.get_or_404(id)
    roles:list[Rol] = Rol.query.filter_by(acteur_id=id).all()

    if roles:
        # Actor has roles, construct a message indicating in which films
        roles_info = "<br>- " + "<br>- ".join([f"'{rol.personage}' in '{Film.query.get(rol.film_id).titel}'" for rol in roles])
        flash(Markup(f'Cannot delete actor because they are assigned to roles:<br>{roles_info}'), 'danger')
        return redirect(url_for('acteur.acteurs'))  # Redirect to actor's detail page or another relevant page
    else:
        # Safe to delete actor
        db.session.delete(acteur)
        db.session.commit()
        flash('Actor successfully deleted', 'success')
        return redirect(url_for('acteur.acteurs'))  # Redirect to the list of actors or another relevant page

app/templates/acteur/acteur_add.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Acteur Toevoegen</h2>
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.voornaam.label(class="form-label") }}
            {{ form.voornaam(class="form-control") }}
            {% if form.voornaam.errors %}
            <div class="invalid-feedback">
                {{ form.voornaam.errors[0] }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.achternaam.label(class="form-label") }}
            {{ form.achternaam(class="form-control") }}
            {% if form.achternaam.errors %}
            <div class="invalid-feedback">
                {{ form.achternaam.errors[0] }}
            </div>
            {% endif %}
        </div>
        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
</div>
{% endblock %}

app/templates/acteur/acteur_edit.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Acteur Bewerken</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.voornaam.label(class="form-label") }}
            {{ form.voornaam(class="form-control") }}
        </div>
        <div class="mb-3">
            {{ form.achternaam.label(class="form-label") }}
            {{ form.achternaam(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Update Acteur</button>
    </form>
</div>
{% endblock %}

app/templates/acteur/acteurs.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">

    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Acteurs</h2>
        <a href="{{ url_for('acteur.acteur_add') }}" class="btn btn-primary">Add New Acteur</a>
    </div>

    <!-- Search Form -->
    <form action="{{ url_for('acteur.acteurs') }}" method="GET" class="mb-3">
        <div class="input-group">
            <input type="text" name="search" class="form-control" placeholder="Search for acteurs...">
            <button type="submit" class="btn btn-outline-secondary">Search</button>
        </div>
    </form>

    {% include 'flash_messages_template.html' %}


    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Voornaam</th>
                    <th>Achternaam</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for acteur in acteurs %}
                <tr>
                    <td>{{ acteur.voornaam }}</td>
                    <td>{{ acteur.achternaam }}</td>
                    <td>
                        <a href="{{ url_for('acteur.acteur_edit', id=acteur.id) }}"
                            class="btn btn-secondary btn-sm">Bewerken</a>
                        <button class="btn btn-danger btn-sm" data-bs-toggle="modal"
                            data-bs-target="#deleteConfirmationModal" data-acteur-id="{{ acteur.id }}">Delete</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this acteur?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="#" class="btn btn-danger" id="deleteActeurBtn">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block extra_js %}
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        var deleteConfirmationModal = document.getElementById('deleteConfirmationModal')
        deleteConfirmationModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            var button = event.relatedTarget
            // Extract info from data-* attributes
            var acteurId = button.getAttribute('data-acteur-id')
            // Update the modal's delete button href
            var deleteButton = deleteConfirmationModal.querySelector('.modal-footer #deleteActeurBtn')
            deleteButton.href = `/acteur/delete/${acteurId}`
        })
    });
</script>
{% endblock %}