app/routes/film.py
import os
import secrets
from flask import Blueprint, current_app, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.forms.forms import CitaatForm, FilmForm, RolForm
from app.models.models import Acteur, Citaat, Film, Regisseur, Rol
from app import db

film_bp = Blueprint('film', __name__, url_prefix='/film')



@film_bp.route('/<int:id>', methods=['GET'])
def film_detail(id):
    form = CitaatForm()
    film: Film = Film.query.get_or_404(id)
    quotes: list[Citaat] = Citaat.query.filter_by(film_id=id).all() 
    rollen = Rol.query.join(Acteur).filter(Rol.film_id==id).all()
    
    return render_template('film/film_detail.html', film=film, rollen=rollen, quotes=quotes, form=form)




def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/film_pics', picture_fn)

    form_picture.save(picture_path)
    return picture_fn
   
@film_bp.route('/add', methods=['GET', 'POST'])
@login_required
def film_add():
    form: FilmForm = FilmForm()
    form.regisseur_id.choices = [(0, 'Choose...')] + [(r.id, r.voornaam + ' '  + r.achternaam) for r in Regisseur.query.all()]

    if form.validate_on_submit():
        if form.poster.data:
            poster_file = save_picture(form.poster.data)
            film = Film(
                titel=form.titel.data,
                regisseur_id=form.regisseur_id.data,
                jaar=form.jaar.data,
                trailer_url=form.trailer_url.data,
                bezoekers=form.bezoekers.data,
                omzet=form.omzet.data,
                overzicht=form.overzicht.data,
                poster_url=poster_file  # Save the path of the uploaded image
            )
        else:
            film = Film(
                titel=form.titel.data, 
                regisseur_id=form.regisseur_id.data,
                jaar=form.jaar.data,
                trailer_url=form.trailer_url.data,
                bezoekers=form.bezoekers.data,
                omzet=form.omzet.data,
                overzicht=form.overzicht.data
            )
        db.session.add(film)
        db.session.commit()
        flash('De film is succesvol toegevoegd!', 'success')
        return redirect(url_for('main.index'))
    return render_template('film/film_add.html', title='Film Toevoegen', form=form)




@film_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_film(id):
    film:Film = Film.query.get_or_404(id)
    form:FilmForm = FilmForm(obj=film)

    form.regisseur_id.choices = [(0, 'Choose...')] + [(r.id, r.voornaam + ' ' + r.achternaam) for r in Regisseur.query.all()]

    if form.validate_on_submit():
        if form.poster.data:
            # Remove old image if exists
            if film.poster_url:
                old_image_path = os.path.join(current_app.root_path, 'static/film_pics', film.poster_url)
                if os.path.exists(old_image_path):
                    os.remove(old_image_path)
            
            # Save new image and update poster_url
            picture_file = save_picture(form.poster.data)
            film.poster_url = picture_file

        # Update other film attributes
        film.titel = form.titel.data
        film.regisseur_id = form.regisseur_id.data
        film.jaar = form.jaar.data
        film.trailer_url = form.trailer_url.data
        film.bezoekers = form.bezoekers.data
        film.omzet = form.omzet.data
        film.overzicht = form.overzicht.data
        
        db.session.commit()
        flash('De film is succesvol bijgewerkt!', 'success')
        return redirect(url_for('film.film_detail', id=film.id))
    
    return render_template('film/film_edit.html', form=form, film=film)



@film_bp.route('/delete/<int:id>')
@login_required
def delete_film(id):
    film:Film = Film.query.get_or_404(id)
    
    # Delete associated roles
    Rol.query.filter_by(film_id=id).delete()
    
    # Delete associated quotes (citaten)
    Citaat.query.filter_by(film_id=id).delete()
    
    # Remove film image if it exists
    if film.poster_url:
        image_path = os.path.join(current_app.root_path, 'static/film_pics', film.poster_url)
        try:
            os.remove(image_path)
        except OSError:
            flash('Error while deleting the image file.', 'warning')

    # Now, delete the film
    db.session.delete(film)
    db.session.commit()
    flash('Film successfully deleted.', 'success')
    return redirect(url_for('main.index'))






@film_bp.route('/<int:id>/add_quote', methods=['POST'])
@login_required
def film_add_quote(id):
    form:CitaatForm = CitaatForm()
    if form.validate_on_submit():
        new_quote = Citaat(inhoud=form.inhoud.data, film_id=id, user_id=current_user.id)
        db.session.add(new_quote)
        db.session.commit()
        flash('Quote successfully added.', 'success')
    return redirect(url_for('film.film_detail', id=id, tab='quotes'))





@film_bp.route('/quote/edit/<int:quote_id>', methods=['GET', 'POST'])
@login_required
def film_edit_quote(quote_id):
    quote:Citaat = Citaat.query.get_or_404(quote_id)
    if quote.user_id != current_user.id:
        flash('You do not have permission to edit this quote.', 'danger')
        return redirect(url_for('main.index'))
    
    form:CitaatForm = CitaatForm(obj=quote)
    if form.validate_on_submit():
        quote.inhoud = form.inhoud.data
        db.session.commit()
        flash('Quote successfully updated.', 'success')
        return redirect(url_for('film.film_detail', id=quote.film_id, tab='quotes'))
    return render_template('edit_quote.html', form=form)  # You'll need to create this template



@film_bp.route('/quote/delete/<int:quote_id>', methods=['GET'])
@login_required
def film_delete_quote(quote_id):
    quote:Citaat = Citaat.query.get_or_404(quote_id)
    if quote.user_id != current_user.id:
        flash('You do not have permission to delete this quote.', 'danger')
        return redirect(url_for('main.index'))
    db.session.delete(quote)
    db.session.commit()
    flash('Quote successfully deleted.', 'success')
    return redirect(url_for('film.film_detail', id=quote.film_id, tab='quotes'))





# ROL FILM

@film_bp.route('/rol/add/<int:film_id>', methods=['GET', 'POST'])  # New route to handle specific film ID
@login_required
def rol_add(film_id):
    form:RolForm = RolForm()
    form.acteur_id.choices = [(0, 'Choose...')] + [(a.id, a.voornaam + ' ' + a.achternaam) for a in Acteur.query.all()]

    if form.validate_on_submit():
        rol:Rol = Rol(
            acteur_id=form.acteur_id.data, 
            film_id=film_id,
            personage=form.personage.data
        )
        db.session.add(rol)
        db.session.commit()
        flash('De Rol is succesvol toegevoegd!', 'success')
        return redirect(url_for('film.film_detail', id=film_id, tab='actors-roles'))
    
    return render_template('film/film_rol_add.html', form=form, film_id=film_id)


@film_bp.route('/rol/edit/<int:id>', methods=['GET', 'POST'])
@login_required  
def rol_edit(id):
    rol:Rol = Rol.query.get_or_404(id)
    form:RolForm = RolForm(obj=rol)
    
    # Update choices for acteur_id
    form.acteur_id.choices = [(0, 'Choose...')] +  [(acteur.id, acteur.voornaam + ' ' + acteur.achternaam) for acteur in Acteur.query.order_by(Acteur.voornaam).all()]
    
    if request.method == 'POST' and form.validate_on_submit():
        rol.acteur_id = form.acteur_id.data
        rol.personage = form.personage.data
        db.session.commit()
        flash('Rol successfully updated!', 'success')
        return redirect(url_for('film.film_detail', id=rol.film_id, tab='actors-roles'))
    
    return render_template('film/film_rol_edit.html', form=form, rol=rol)


@film_bp.route('/rol/delete/<int:id>', methods=['GET'])
@login_required
def rol_delete(id):
    rol:Rol = Rol.query.get_or_404(id)
    film_id = rol.film_id
    db.session.delete(rol)
    db.session.commit()
    flash('De Rol is succesvol verwijderd!', 'success')
    return redirect(url_for('film.film_detail', id=film_id, tab='actors-roles'))

app/templates/film/film_add.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Film Toevoegen</h2>
    <form action="" method="POST" enctype="multipart/form-data"> <!-- Add enctype attribute here -->
        {{ form.hidden_tag() }}
        <div class="mb-3 form-group">
            {{ form.titel.label }} <span class="text-danger">*</span>
            {{ form.titel(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.regisseur_id.label }} <span class="text-danger">*</span>
            {{ form.regisseur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.jaar.label }} <span class="text-danger">*</span>
            {{ form.jaar(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.trailer_url.label }}
            {{ form.trailer_url(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.bezoekers.label }}
            {{ form.bezoekers(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.omzet.label }}
            {{ form.omzet(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.overzicht.label }}
            {{ form.overzicht(class="form-control") }}
        </div>
        <!-- Add a file input field for the poster -->
        <div class="mb-3 form-group">
            {{ form.poster.label }}
            {{ form.poster(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}

app/templates/film/film_add_quote.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <h2>Add Quote</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.inhoud.label }}
            {{ form.inhoud(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

app/templates/film/film_detail.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">


    {% include 'flash_messages_template.html' %}

    <div class="d-flex justify-content-between align-items-center mb-4">

        <h2>{{ film.titel }}</h2>

        <div>
            {% if current_user.is_authenticated %}
            <!-- Dropdown button -->
            <div class="btn-group">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="filmActionsDropdown"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    Film Actions
                </button>
                <ul class="dropdown-menu" aria-labelledby="filmActionsDropdown">
                    <!-- Bewerken Film option -->
                    <li><a class="dropdown-item" href="{{ url_for('film.edit_film', id=film.id) }}">Bewerken Film</a>
                    </li>
                    <!-- Delete Film option -->
                    <li><a class="dropdown-item text-danger" href="#" data-bs-toggle="modal"
                            data-bs-target="#deleteConfirmationModal" data-film-id="{{ film.id }}">Delete Film</a></li>

                </ul>
            </div>
            {% endif %}
        </div>
    </div>


    <ul class="nav nav-tabs" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
            <button class="nav-link active" id="film-details-tab" data-bs-toggle="tab" data-bs-target="#film-details"
                type="button" role="tab" aria-controls="film-details" aria-selected="true">Film Details</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="actors-roles-tab" data-bs-toggle="tab" data-bs-target="#actors-roles"
                type="button" role="tab" aria-controls="actors-roles" aria-selected="false">Actors & Roles</button>
        </li>
        <li class="nav-item" role="presentation">
            <button class="nav-link" id="quotes-tab" data-bs-toggle="tab" data-bs-target="#quotes" type="button"
                role="tab" aria-controls="quotes" aria-selected="false">Quotes</button>
        </li>
    </ul>


    <div class="tab-content" id="myTabContent">
        <!-- Film Details Tab Pane -->
        <div class="tab-pane fade show active" id="film-details" role="tabpanel" aria-labelledby="film-details-tab">
            <!-- Film details content goes here -->
            <div class="row mt-4">
                <div class="col-md-8">
                    <p><strong>Regisseur:</strong> {{ film.regisseur.voornaam }} {{ film.regisseur.achternaam }}</p>
                    <p><strong>Jaar:</strong> {{ film.jaar }}</p>
                    <p><strong>Bezoekers:</strong> {{ film.bezoekers }}</p>
                    <p><strong>Omzet:</strong> {{ film.omzet }}</p>
                    <p><strong>Overzicht:</strong> {{ film.overzicht }}</p>
                    <p><strong>Trailer URL:</strong> <a href="{{ film.trailer_url }}" target="_blank">{{
                            film.trailer_url }}</a>
                    </p>

                    {% if film.trailer_url %}
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item"
                            src="https://www.youtube.com/embed/{{ film.trailer_url.split('v=')[1] }}" frameborder="0"
                            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                    </div>
                    {% endif %}

                </div>
                <div class="col-md-4">
                    <!-- If you have an image or poster for the film, you can display it here -->
                    {% if film.poster_url %}
                    <img src="{{ url_for('static', filename='film_pics/' + film.poster_url) }}"
                        class="img-fluid rounded" alt="{{ film.titel }}">
                    {% else %}
                    <img src="{{ url_for('static', filename='film_pics/no_image_available.png') }}"
                        class="img-fluid rounded" alt="No image available">
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- Actors & Roles Tab Pane -->
        <div class="tab-pane fade" id="actors-roles" role="tabpanel" aria-labelledby="actors-roles-tab">
            <!-- Actors & Roles content goes here -->
            <div class="container mt-4">

                <div class="d-flex justify-content-between align-items-center">
                    <h3>Acteurs en Rollen</h3>
                    <a href="{{ url_for('film.rol_add', film_id=film.id) }}" class="btn btn-primary">Add New Role</a>
                </div>


                <div class="row">
                    {% for rol in rollen %}
                    <div class="col-md-6 mb-3">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ rol.acteur.voornaam }} {{ rol.acteur.achternaam }}</h5>
                                <p class="card-text"><strong>Als:</strong> {{ rol.personage }}</p>
                                <!-- Add Bewerken and Delete buttons here -->
                                <div class="text-end"> <!-- Adjust alignment as needed -->
                                    <a href="{{ url_for('film.rol_edit', id=rol.id) }}"
                                        class="btn btn-sm btn-secondary">Bewerken</a>
                                    <a href="{{ url_for('film.rol_delete', id=rol.id) }}" class="btn btn-sm btn-danger"
                                        onclick="return confirm('Weet je het zeker?');">Delete</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <p>Geen rollen gevonden.</p>
                    {% endfor %}
                </div>

            </div>
        </div>



        <!-- Quotes Tab Pane -->
        <div class="tab-pane fade" id="quotes" role="tabpanel" aria-labelledby="quotes-tab">
            <div class="container mt-4">
                <h3>Citaat</h3>
                {% for quote in quotes %}



                <blockquote class="blockquote d-flex justify-content-between align-items-center">
                    <div class="flex-grow-1">
                        <p class="mb-1">{{ quote.inhoud }}</p>
                        <footer class="blockquote-footer">Posted by {{ quote.user.username }}</footer>
                    </div>
                    <!-- Check if the current user is the creator of the quote -->
                    {% if current_user.is_authenticated and quote.user_id == current_user.id %}
                    <div class="dropdown">
                        <button class="btn btn-sm btn-secondary dropdown-toggle" type="button"
                            id="dropdownMenuButton{{ quote.id }}" data-bs-toggle="dropdown" aria-expanded="false">
                            Actions
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton{{ quote.id }}">
                            <!-- <li><a class="dropdown-item"
                                    href="{{ url_for('film.film_edit_quote', quote_id=quote.id) }}">Bewerken</a></li> -->
                            <li><a class="dropdown-item text-danger"
                                    href="{{ url_for('film.film_delete_quote', quote_id=quote.id) }}"
                                    onclick="return confirm('Are you sure?');">Delete</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </blockquote>
                {% else %}
                <p>No quotes yet.</p>
                {% endfor %}


                {% if current_user.is_authenticated %}
                <h4>Add a new Citaat</h4>
                <form action="{{ url_for('film.film_add_quote', id=film.id) }}" method="POST">

                    {{ form.hidden_tag() }}
                    <div class="form-group">
                        {{ form.inhoud.label }}
                        {{ form.inhoud(class="form-control") }}
                    </div>
                    {{ form.submit(class="btn btn-primary") }}
                </form>
                {% endif %}
            </div>
        </div>


    </div>



</div>






<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this Movie?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="#" class="btn btn-danger" id="deleteFilmBtn">Delete</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block extra_js %}
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        var deleteConfirmationModal = document.getElementById('deleteConfirmationModal')
        deleteConfirmationModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            var button = event.relatedTarget
            // Update the modal's delete button href
            var deleteButton = deleteConfirmationModal.querySelector('.modal-footer #deleteFilmBtn')
            deleteButton.href = "{{ url_for('film.delete_film', id=film.id) }}"
        })


        // Check for the 'tab' query parameter and activate the corresponding tab
        const urlParams = new URLSearchParams(window.location.search);
        const activeTab = urlParams.get('tab');

        if (activeTab) {
            const newActiveTab = document.querySelector(`#${activeTab}-tab`);
            const newActivePane = document.querySelector(`#${activeTab}`);

            // Deactivate the currently active tab and pane
            document.querySelector('.nav-link.active').classList.remove('active');
            document.querySelector('.tab-pane.show.active').classList.remove('show', 'active');

            // Activate the specified tab and pane
            if (newActiveTab && newActivePane) {
                newActiveTab.classList.add('active');
                newActivePane.classList.add('show', 'active');
            }
        }

    });
</script>
{% endblock %}

app/templates/film/film_edit.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Film Bewerken</h2>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}


    <form action="{{ url_for('film.edit_film', id=film.id) }}" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="mb-3 form-group">
            {{ form.titel.label }} <span class="text-danger">*</span>
            {{ form.titel(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.regisseur_id.label }} <span class="text-danger">*</span>
            {{ form.regisseur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.jaar.label }} <span class="text-danger">*</span>
            {{ form.jaar(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.trailer_url.label }}
            {{ form.trailer_url(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.bezoekers.label }}
            {{ form.bezoekers(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.omzet.label }}
            {{ form.omzet(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.overzicht.label }}
            {{ form.overzicht(class="form-control") }}
        </div>


        <!-- Current Film Poster -->
        {% if film.poster_url %}
        <div class="mb-3">
            <label>Current Film Poster:</label>
            <div>
                <img src="{{ url_for('static', filename='film_pics/' + film.poster_url) }}" alt="Film Poster"
                    style="max-width: 200px;">
            </div>
        </div>
        {% endif %}


        <!-- File Upload for New Poster -->
        <div class="mb-3 form-group">
            {{ form.poster.label }}
            {{ form.poster(class="form-control") }}
        </div>

        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{{ url_for('film.film_detail', id=film.id) }}" class="btn btn-secondary">Cancel</a>

    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}

app/templates/film/film_rol_add.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Rol Toevoegen/Bewerken</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3 form-group">
            {{ form.acteur_id.label }} <span class="text-danger">*</span>
            {{ form.acteur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.personage.label(class="form-label") }} <span class="text-danger">*</span>
            {{ form.personage(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}

app/templates/film/film_rol_edit.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Rol Bewerken</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.acteur_id.label }} <span class="text-danger">*</span>
            {{ form.acteur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3">
            {{ form.personage.label }} <span class="text-danger">*</span>
            {{ form.personage(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Update Rol</button>
    </form>
</div>
{% endblock %}


{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}