app/routes/auth.py
from app import db, bcrypt
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_user, logout_user, login_required
from app.forms.forms import LoginForm, RegistratieForm

from app.models.models import Gebruiker


auth_bp = Blueprint('auth', __name__, url_prefix='/auth')


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        gebruiker:Gebruiker = Gebruiker.query.filter_by(email=form.email.data).first()
        if gebruiker and bcrypt.check_password_hash(gebruiker.wachtwoord_hash, form.wachtwoord.data):
            login_user(gebruiker, remember=form.remember_me.data)
            flash('Succesvol ingelogd.', 'success')

            next_page = request.args.get('next')
            if not next_page or not next_page.startswith('/'):
                next_page = url_for('main.index')
            return redirect(next_page)
        else:
            flash('Login mislukt. Controleer e-mail en wachtwoord.', 'danger')
    
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Je bent nu uitgelogd!')
    return redirect(url_for('main.index'))


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form:RegistratieForm = RegistratieForm()
    if form.validate_on_submit():
        new_user:Gebruiker = Gebruiker(username=form.username.data, email=form.email.data, wachtwoord=form.wachtwoord.data)
        db.session.add(new_user)
        db.session.commit()
        flash('Je account is aangemaakt. Je kunt nu inloggen.', 'success')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form)

app/routes/film.py
import os
import secrets
from flask import Blueprint, current_app, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from app.forms.forms import CitaatForm, FilmForm, RolForm
from app.models.models import Acteur, Citaat, Film, Regisseur, Rol
from app import db

film_bp = Blueprint('film', __name__, url_prefix='/film')



@film_bp.route('/<int:id>', methods=['GET'])
def film_detail(id):
    form = CitaatForm()
    film: Film = Film.query.get_or_404(id)
    quotes: list[Citaat] = Citaat.query.filter_by(film_id=id).all() 
    rollen = Rol.query.join(Acteur).filter(Rol.film_id==id).all()
    
    return render_template('film/film_detail.html', film=film, rollen=rollen, quotes=quotes, form=form)




def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/film_pics', picture_fn)

    form_picture.save(picture_path)
    return picture_fn
   
@film_bp.route('/add', methods=['GET', 'POST'])
@login_required
def film_add():
    form: FilmForm = FilmForm()
    form.regisseur_id.choices = [(0, 'Choose...')] + [(r.id, r.voornaam + ' '  + r.achternaam) for r in Regisseur.query.all()]

    if form.validate_on_submit():
        if form.poster.data:
            poster_file = save_picture(form.poster.data)
            film = Film(
                titel=form.titel.data,
                regisseur_id=form.regisseur_id.data,
                jaar=form.jaar.data,
                trailer_url=form.trailer_url.data,
                bezoekers=form.bezoekers.data,
                omzet=form.omzet.data,
                overzicht=form.overzicht.data,
                poster_url=poster_file  # Save the path of the uploaded image
            )
        else:
            film = Film(
                titel=form.titel.data, 
                regisseur_id=form.regisseur_id.data,
                jaar=form.jaar.data,
                trailer_url=form.trailer_url.data,
                bezoekers=form.bezoekers.data,
                omzet=form.omzet.data,
                overzicht=form.overzicht.data
            )
        db.session.add(film)
        db.session.commit()
        flash('De film is succesvol toegevoegd!', 'success')
        return redirect(url_for('main.index'))
    return render_template('film/film_add.html', title='Film Toevoegen', form=form)




@film_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_film(id):
    film:Film = Film.query.get_or_404(id)
    form:FilmForm = FilmForm(obj=film)

    form.regisseur_id.choices = [(0, 'Choose...')] + [(r.id, r.voornaam + ' ' + r.achternaam) for r in Regisseur.query.all()]

    if form.validate_on_submit():
        if form.poster.data:
            # Remove old image if exists
            if film.poster_url:
                old_image_path = os.path.join(current_app.root_path, 'static/film_pics', film.poster_url)
                if os.path.exists(old_image_path):
                    os.remove(old_image_path)
            
            # Save new image and update poster_url
            picture_file = save_picture(form.poster.data)
            film.poster_url = picture_file

        # Update other film attributes
        film.titel = form.titel.data
        film.regisseur_id = form.regisseur_id.data
        film.jaar = form.jaar.data
        film.trailer_url = form.trailer_url.data
        film.bezoekers = form.bezoekers.data
        film.omzet = form.omzet.data
        film.overzicht = form.overzicht.data
        
        db.session.commit()
        flash('De film is succesvol bijgewerkt!', 'success')
        return redirect(url_for('film.film_detail', id=film.id))
    
    return render_template('film/film_edit.html', form=form, film=film)



@film_bp.route('/delete/<int:id>')
@login_required
def delete_film(id):
    film:Film = Film.query.get_or_404(id)
    
    # Delete associated roles
    Rol.query.filter_by(film_id=id).delete()
    
    # Delete associated quotes (citaten)
    Citaat.query.filter_by(film_id=id).delete()
    
    # Remove film image if it exists
    if film.poster_url:
        image_path = os.path.join(current_app.root_path, 'static/film_pics', film.poster_url)
        try:
            os.remove(image_path)
        except OSError:
            flash('Error while deleting the image file.', 'warning')

    # Now, delete the film
    db.session.delete(film)
    db.session.commit()
    flash('Film successfully deleted.', 'success')
    return redirect(url_for('main.index'))






@film_bp.route('/<int:id>/add_quote', methods=['POST'])
@login_required
def film_add_quote(id):
    form:CitaatForm = CitaatForm()
    if form.validate_on_submit():
        new_quote = Citaat(inhoud=form.inhoud.data, film_id=id, user_id=current_user.id)
        db.session.add(new_quote)
        db.session.commit()
        flash('Quote successfully added.', 'success')
    return redirect(url_for('film.film_detail', id=id, tab='quotes'))





@film_bp.route('/quote/edit/<int:quote_id>', methods=['GET', 'POST'])
@login_required
def film_edit_quote(quote_id):
    quote:Citaat = Citaat.query.get_or_404(quote_id)
    if quote.user_id != current_user.id:
        flash('You do not have permission to edit this quote.', 'danger')
        return redirect(url_for('main.index'))
    
    form:CitaatForm = CitaatForm(obj=quote)
    if form.validate_on_submit():
        quote.inhoud = form.inhoud.data
        db.session.commit()
        flash('Quote successfully updated.', 'success')
        return redirect(url_for('film.film_detail', id=quote.film_id, tab='quotes'))
    return render_template('edit_quote.html', form=form)  # You'll need to create this template



@film_bp.route('/quote/delete/<int:quote_id>', methods=['GET'])
@login_required
def film_delete_quote(quote_id):
    quote:Citaat = Citaat.query.get_or_404(quote_id)
    if quote.user_id != current_user.id:
        flash('You do not have permission to delete this quote.', 'danger')
        return redirect(url_for('main.index'))
    db.session.delete(quote)
    db.session.commit()
    flash('Quote successfully deleted.', 'success')
    return redirect(url_for('film.film_detail', id=quote.film_id, tab='quotes'))





# ROL FILM

@film_bp.route('/rol/add/<int:film_id>', methods=['GET', 'POST'])  # New route to handle specific film ID
@login_required
def rol_add(film_id):
    form:RolForm = RolForm()
    form.acteur_id.choices = [(0, 'Choose...')] + [(a.id, a.voornaam + ' ' + a.achternaam) for a in Acteur.query.all()]

    if form.validate_on_submit():
        rol:Rol = Rol(
            acteur_id=form.acteur_id.data, 
            film_id=film_id,
            personage=form.personage.data
        )
        db.session.add(rol)
        db.session.commit()
        flash('De Rol is succesvol toegevoegd!', 'success')
        return redirect(url_for('film.film_detail', id=film_id, tab='actors-roles'))
    
    return render_template('film/film_rol_add.html', form=form, film_id=film_id)


@film_bp.route('/rol/edit/<int:id>', methods=['GET', 'POST'])
@login_required  
def rol_edit(id):
    rol:Rol = Rol.query.get_or_404(id)
    form:RolForm = RolForm(obj=rol)
    
    # Update choices for acteur_id
    form.acteur_id.choices = [(0, 'Choose...')] +  [(acteur.id, acteur.voornaam + ' ' + acteur.achternaam) for acteur in Acteur.query.order_by(Acteur.voornaam).all()]
    
    if request.method == 'POST' and form.validate_on_submit():
        rol.acteur_id = form.acteur_id.data
        rol.personage = form.personage.data
        db.session.commit()
        flash('Rol successfully updated!', 'success')
        return redirect(url_for('film.film_detail', id=rol.film_id, tab='actors-roles'))
    
    return render_template('film/film_rol_edit.html', form=form, rol=rol)


@film_bp.route('/rol/delete/<int:id>', methods=['GET'])
@login_required
def rol_delete(id):
    rol:Rol = Rol.query.get_or_404(id)
    film_id = rol.film_id
    db.session.delete(rol)
    db.session.commit()
    flash('De Rol is succesvol verwijderd!', 'success')
    return redirect(url_for('film.film_detail', id=film_id, tab='actors-roles'))

app/routes/regisseur.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required
from app.forms.forms import RegisseurForm
from app.models.models import Regisseur
from app import db

regisseur_bp = Blueprint('regisseur', __name__, url_prefix='/regisseur')

@regisseur_bp.route('/', methods=['GET'])
def regisseurs():
    search_query = request.args.get('search', '')
    if search_query:
        regisseurs = Regisseur.query.filter(
            db.or_(
                Regisseur.voornaam.ilike(f'%{search_query}%'),
                Regisseur.achternaam.ilike(f'%{search_query}%')
            )
        ).all()
    else:
        regisseurs:list[Regisseur] = Regisseur.query.all()
    
    return render_template('regisseur/regisseurs.html', regisseurs=regisseurs)



@regisseur_bp.route('/add', methods=['GET', 'POST'])
@login_required
def regisseur_add():
    form: RegisseurForm = RegisseurForm()
    if form.validate_on_submit():
        regisseur = Regisseur(voornaam=form.voornaam.data, achternaam=form.achternaam.data)
        db.session.add(regisseur)
        db.session.commit()
        flash('De regisseur is succesvol toegevoegd!', 'success')
        return redirect(url_for('regisseur.regisseurs'))
    return render_template('regisseur/regisseur_add.html', form=form)


@regisseur_bp.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def regisseur_edit(id):
    regisseur:Regisseur = Regisseur.query.get_or_404(id)
    form = RegisseurForm(obj=regisseur)
    
    if form.validate_on_submit():
        regisseur.voornaam = form.voornaam.data
        regisseur.achternaam = form.achternaam.data
        
        db.session.commit()
        flash('De regisseur is succesvol bijgewerkt!', 'success')
        return redirect(url_for('regisseur.regisseurs', id=regisseur.id))
    
    return render_template('regisseur/regisseur_edit.html', form=form)


@regisseur_bp.route('/delete/<int:id>')
@login_required
def delete_regisseur(id):
    regisseur:Regisseur = Regisseur.query.get_or_404(id)
    if regisseur.films:
        flash('Cannot delete a Regisseur connected to films.', 'danger')
    else:
        db.session.delete(regisseur)
        db.session.commit()
        flash('Regisseur successfully deleted.', 'success')
    return redirect(url_for('regisseur.regisseurs'))

app/templates/base.html
<!DOCTYPE html>
<html lang="nl">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FilmApp</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/carousel.css') }}" rel="stylesheet">

    {% block extra_head %}{% endblock %}
</head>

<body>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="container-fluid">
                    <a class="navbar-brand" href="{{ url_for('main.index') }}">Nederlandse Films</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                        aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarCollapse">
                        <ul class="navbar-nav me-auto mb-2 mb-md-0">
                            <li class="nav-item">
                                <a class="nav-link{{ ' active' if request.path == url_for('main.index') else '' }}"
                                    aria-current="page" href="{{ url_for('main.index') }}">Home</a>
                            </li>

                            {% if current_user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link{{ ' active' if request.path == url_for('regisseur.regisseurs') else '' }}"
                                    href="{{ url_for('regisseur.regisseurs') }}">Regisseurs</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link{{ ' active' if request.path == url_for('acteur.acteurs') else '' }}"
                                    href="{{ url_for('acteur.acteurs') }}">Acteurs</a>
                            </li>
                            {% endif %}
                        </ul>

                        <div class="d-flex align-items-center">
                            {% if current_user.is_authenticated %}
                            <span class="navbar-text me-2">{{ current_user.username }}</span>
                            <a class="btn btn-secondary me-2" href="{{ url_for('auth.logout') }}">Uitloggen</a>
                            {% else %}
                            <a class="btn btn-secondary me-2" href="{{ url_for('auth.login') }}">Inloggen</a>
                            <a class="btn btn-secondary" href="{{ url_for('auth.register') }}">Registreren</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
        </header>

        <main>
            {% block content %}{% endblock %}
        </main>

        <!-- Bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>

        {% block extra_js %}{% endblock %}
    </body>

</html>

app/templates/flash_messages_template.html
<!-- Display global form errors -->
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

app/templates/index.html
{% extends "base.html" %}


{% block extra_head %}
<style>
    .card {
        transition: transform .2s;
        /* Animation */
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
    }



    .card-title {
        font-size: 1.25rem;
        /* Larger title font */
        font-weight: bold;
    }

    .card-text {
        font-size: 0.9rem;
        /* Slightly smaller text for details */
    }

    .btn-primary {
        background-color: #007bff;
        border: none;
    }

    .btn-primary:hover {
        background-color: #0056b3;
    }
</style>
{% endblock %}


{% block content %}
<div class="container mt-4">

    {% include 'flash_messages_template.html' %}

    <div class="d-flex justify-content-between align-items-center">
        <h1>Nederlandse Films</h1>

        {% if current_user.is_authenticated %}
        <a href="{{ url_for('film.film_add') }}" class="btn btn-primary">Add New Film</a>
        {% endif %}
    </div>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for film in films %}
        <div class="col">
            <div class="card h-100">
                {% if film.poster_url %}
                <img src="{{ url_for('static', filename='film_pics/' + film.poster_url) }}" class="card-img-top"
                    alt="{{ film.titel }}">
                {% else %}
                <img src="{{ url_for('static', filename='film_pics/no_image_available.png') }}" class="card-img-top"
                    alt="No image available">
                {% endif %}

                <div class="card-body">
                    <h5 class="card-title">{{ film.titel }}</h5>
                    <p class="card-text">Regisseur: {{ film.regisseur.voornaam }} {{ film.regisseur.achternaam }}</p>
                    <p class="card-text">Jaar: {{ film.jaar }}</p>
                    <a href="{{ url_for('film.film_detail', id=film.id) }}" class="btn btn-primary">Lees Meer</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

app/templates/regisseurs.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center">
        <h2>Regisseurs</h2>
        <a href="{{ url_for('main.add_regisseur') }}" class="btn btn-primary">Add New Regisseur</a>
    </div>

    {% include 'flash_messages_template.html' %}


    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Voornaam</th>
                    <th>Achternaam</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for regisseur in regisseurs %}
                <tr>
                    <td>{{ regisseur.id }}</td>
                    <td>{{ regisseur.voornaam }}</td>
                    <td>{{ regisseur.achternaam }}</td>
                    <td>
                        <a href="{{ url_for('main.edit_regisseur', id=regisseur.id) }}"
                            class="btn btn-secondary btn-sm">Edit</a>
                        <button class="btn btn-danger btn-sm" data-bs-toggle="modal"
                            data-bs-target="#deleteConfirmationModal"
                            data-regisseur-id="{{ regisseur.id }}">Delete</button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteConfirmationModal" tabindex="-1" aria-labelledby="deleteConfirmationModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteConfirmationModalLabel">Confirm Delete</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this regisseur?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <a href="#" class="btn btn-danger" id="deleteRegisseurBtn">Delete</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block extra_js %}
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        var deleteConfirmationModal = document.getElementById('deleteConfirmationModal')
        deleteConfirmationModal.addEventListener('show.bs.modal', function (event) {
            // Button that triggered the modal
            var button = event.relatedTarget
            // Extract info from data-* attributes
            var regisseurId = button.getAttribute('data-regisseur-id')
            // Update the modal's delete button href
            var deleteButton = deleteConfirmationModal.querySelector('.modal-footer #deleteRegisseurBtn')
            deleteButton.href = `/regisseur/delete/${regisseurId}`
        })
    });
</script>
{% endblock %}

app/templates/regisseurs_add.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Film Toevoegen</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3 form-group">
            {{ form.titel.label }}
            {{ form.titel(class="form-control") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.regisseur_id.label }}
            {{ form.regisseur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.jaar.label }}
            {{ form.jaar(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary ">Submit</button>
    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}

app/templates/rol_add.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Rol Toevoegen/Bewerken</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3 form-group">
            {{ form.acteur_id.label }} <span class="text-danger">*</span>
            {{ form.acteur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.film_id.label }} <span class="text-danger">*</span>
            {{ form.film_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3 form-group">
            {{ form.personage.label(class="form-label") }} <span class="text-danger">*</span>
            {{ form.personage(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}

app/templates/rol_edit.html
{% extends "base.html" %}

{% block extra_head %}
<link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/css/bootstrap-select.min.css">
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Rol Bewerken</h2>
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="mb-3">
            {{ form.acteur_id.label }} <span class="text-danger">*</span>
            {{ form.acteur_id(class="form-control selectpicker", data_live_search="true") }}
        </div>
        <div class="mb-3">
            {{ form.personage.label }} <span class="text-danger">*</span>
            {{ form.personage(class="form-control") }}
        </div>
        <button type="submit" class="btn btn-primary">Update Rol</button>
    </form>
</div>
{% endblock %}


{% block extra_js %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.14.0-beta3/dist/js/bootstrap-select.min.js"></script>
<script>
    $(document).ready(function () {
        $('.selectpicker').selectpicker();
    });
</script>
{% endblock %}